Repository datalad/datalad-container, pull requests merged in 2023-06, with the labels that each got.

#208 Capture stderr as well while trying for singularity or apptainer to avoid spurious stderr display
  changelog.d/pr-208.md
  datalad_container/extractors/_load_singularity_versions.py
Labels: patch

#209 BF: by default stop containers-run on error, to not proceed to save
  changelog.d/pr-209.md
  datalad_container/containers_run.py
  datalad_container/tests/test_run.py
Labels: patch, release

#213 Fix docs builds
  docs/source/conf.py
Labels: documentation

#212 Make install-singularity.sh fail if any step fails
  .appveyor.yml
  tools/ci/install-singularity.sh
Labels: tests
